#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

INSTALLDIR=/opt/freebox_hosts
PROG=$INSTALLDIR/.venv/bin/freebox-hosts
HOSTS_FILE=/tmp/hosts/freebox.hosts

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --hosts-file "$HOSTS_FILE"
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}
